# Generated by Django 3.1.6 on 2021-03-10 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='Cedula')),
                ('Nombres', models.CharField(max_length=50, verbose_name='Nombres')),
                ('Apellidos', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('Telefono', models.CharField(max_length=20, verbose_name='Telefono')),
                ('Direccion', models.CharField(max_length=50, verbose_name='Direccion')),
                ('email', models.EmailField(max_length=50, verbose_name='Correo')),
                ('Cargo', models.IntegerField(choices=[[1, 'Veterinario'], [2, 'Recepcionista']], verbose_name='Cargo')),
                ('usuario_activo', models.BooleanField(default=True)),
                ('usuario_administrador', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
