# Generated by Django 3.1.6 on 2021-03-15 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('Apellido', models.CharField(max_length=50, verbose_name='Apellido')),
                ('Telefono', models.CharField(max_length=20, verbose_name='Telefono')),
                ('Direccion', models.CharField(max_length=50, verbose_name='Direccion')),
                ('Correo', models.EmailField(max_length=50, verbose_name='Correo')),
                ('Cedula', models.CharField(max_length=20, verbose_name='Cedula')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['Nombre'],
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Codigo', models.CharField(max_length=50, verbose_name='Codigo')),
                ('Nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('Cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('Valor', models.IntegerField(verbose_name='Valor')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['Nombre'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='Cedula')),
                ('Nombres', models.CharField(max_length=50, verbose_name='Nombres')),
                ('Apellidos', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('Telefono', models.CharField(max_length=20, verbose_name='Telefono')),
                ('Direccion', models.CharField(max_length=50, verbose_name='Direccion')),
                ('email', models.EmailField(max_length=50, verbose_name='Correo')),
                ('Cargo', models.IntegerField(choices=[[1, 'Veterinario'], [2, 'Recepcionista']], verbose_name='Cargo')),
                ('usuario_activo', models.BooleanField(default=True)),
                ('usuario_administrador', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['Nombres'],
            },
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=20, verbose_name='Nombre')),
                ('Especie', models.CharField(max_length=20, verbose_name='Especie')),
                ('Raza', models.CharField(max_length=20, verbose_name='Raza')),
                ('Fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('Sexo', models.IntegerField(choices=[[1, 'Macho'], [2, 'Hembra']], verbose_name='Sexo')),
                ('Cliente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cliente')),
            ],
            options={
                'verbose_name': 'Mascota',
                'verbose_name_plural': 'Mascotas',
                'ordering': ['Nombre'],
            },
        ),
    ]
