# Generated by Django 3.1.6 on 2021-03-08 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=20)),
                ('Apellido', models.CharField(max_length=20)),
                ('Telefono', models.CharField(max_length=20)),
                ('Direccion', models.CharField(max_length=20)),
                ('Correo', models.EmailField(max_length=20)),
                ('Cargo', models.IntegerField(max_length=20)),
                ('Activo', models.BooleanField(null=True)),
                ('Cedula', models.CharField(max_length=20)),
                ('Contraseña', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['Nombre'],
            },
        ),
    ]
