# Generated by Django 3.1.6 on 2021-03-12 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=20)),
                ('Apellido', models.CharField(max_length=20)),
                ('Telefono', models.CharField(max_length=20)),
                ('Direccion', models.CharField(max_length=50)),
                ('Correo', models.EmailField(max_length=50)),
                ('Cedula', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['Nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['Nombres'], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
    ]
