# Generated by Django 3.1.7 on 2021-04-01 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210314_2128'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicio',
            options={'ordering': ['Codigo'], 'verbose_name': 'Servicio', 'verbose_name_plural': 'Servicios'},
        ),
        migrations.CreateModel(
            name='Historia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha_creacion', models.DateField(verbose_name='Fecha de Creación')),
                ('Mascota_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.mascota')),
            ],
            options={
                'verbose_name': 'Historia',
                'verbose_name_plural': 'Historias',
                'ordering': ['id'],
            },
        ),
    ]
