# Generated by Django 3.1.6 on 2021-03-12 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210311_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='Apellido',
            field=models.CharField(max_length=50, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='Cedula',
            field=models.CharField(max_length=20, verbose_name='Cedula'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='Correo',
            field=models.EmailField(max_length=50, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='Direccion',
            field=models.CharField(max_length=50, verbose_name='Direccion'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='Nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='Telefono',
            field=models.CharField(max_length=20, verbose_name='Telefono'),
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=20, verbose_name='Nombre')),
                ('Especie', models.CharField(max_length=20, verbose_name='Especie')),
                ('Raza', models.CharField(max_length=20, verbose_name='Raza')),
                ('Fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('Sexo', models.IntegerField(choices=[[1, 'Macho'], [2, 'Hembra']], verbose_name='Sexo')),
                ('Cliente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cliente')),
            ],
            options={
                'verbose_name': 'Mascota',
                'verbose_name_plural': 'Mascota',
                'ordering': ['Nombre'],
            },
        ),
    ]
