# Generated by Django 3.1.6 on 2021-03-12 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_cliente'),
        ('app', '0003_auto_20210311_2127'),
    ]

    operations = [
    ]
