# Generated by Django 3.1.7 on 2021-04-01 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210401_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntradaHistoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Veterinario', models.CharField(max_length=50, verbose_name='Veterinario')),
                ('Fecha', models.DateField(verbose_name='Fecha')),
                ('Hora', models.DateTimeField(verbose_name='Hora')),
                ('Observaciones', models.CharField(max_length=500, verbose_name='Observaciones')),
                ('Tipo', models.CharField(max_length=50, verbose_name='Tipo')),
                ('Historia_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.historia')),
            ],
            options={
                'verbose_name': 'EntradaHistoria',
                'verbose_name_plural': 'EntradasHistorias',
                'ordering': ['id'],
            },
        ),
    ]
