# Generated by Django 3.1.7 on 2021-04-01 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_entradahistoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entradahistoria',
            name='Hora',
        ),
        migrations.AlterField(
            model_name='entradahistoria',
            name='Fecha',
            field=models.DateTimeField(verbose_name='Hora'),
        ),
    ]
