# Generated by Django 3.1.6 on 2021-04-08 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210401_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradahistoria',
            name='Fecha',
            field=models.DateTimeField(verbose_name='Fecha'),
        ),
    ]
