# Generated by Django 3.1.6 on 2021-04-11 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_historia_bobada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historia',
            name='bobada',
        ),
    ]
