# Generated by Django 3.1.5 on 2021-04-14 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_historia_bobada'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entradahistoria',
            options={'ordering': ['Fecha'], 'verbose_name': 'EntradaHistoria', 'verbose_name_plural': 'EntradasHistorias'},
        ),
        migrations.AlterField(
            model_name='entradahistoria',
            name='Fecha',
            field=models.DateField(verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='entradahistoria',
            name='Observaciones',
            field=models.CharField(max_length=2000, verbose_name='Observaciones'),
        ),
    ]
