# Generated by Django 3.1.7 on 2021-04-15 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210414_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='Cedula',
            field=models.CharField(max_length=20, unique=True, verbose_name='Cedula'),
        ),
        migrations.AlterField(
            model_name='historia',
            name='Mascota_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.mascota', unique=True),
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha', models.DateField(blank=True, verbose_name='Fecha Compra')),
                ('Hora', models.DateField(blank=True, verbose_name='Hora Compra')),
                ('total', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='total')),
                ('Cliente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cliente')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['Fecha'],
            },
        ),
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('id_Factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.factura')),
                ('id_Servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.servicio')),
            ],
            options={
                'verbose_name': 'DetalleFactura',
                'verbose_name_plural': 'DetalleFactura',
                'ordering': ['id_Factura'],
            },
        ),
    ]
