# Generated by Django 3.1.7 on 2021-04-15 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210415_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradahistoria',
            name='Fecha',
            field=models.DateTimeField(verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='Hora',
            field=models.DateTimeField(blank=True, verbose_name='Hora Compra'),
        ),
    ]
