# Generated by Django 3.1.7 on 2021-04-15 21:15

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20210415_1710'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detallefactura',
            options={'ordering': ['Factura_id'], 'verbose_name': 'DetalleFactura', 'verbose_name_plural': 'DetalleFactura'},
        ),
        migrations.RenameField(
            model_name='detallefactura',
            old_name='id_Factura',
            new_name='Factura_id',
        ),
        migrations.RenameField(
            model_name='detallefactura',
            old_name='id_Servicio',
            new_name='Servicio_id',
        ),
        migrations.AddField(
            model_name='entradahistoria',
            name='Hora',
            field=models.CharField(default=app.models.get_default_my_hour, max_length=50),
        ),
        migrations.AlterField(
            model_name='factura',
            name='Hora',
            field=models.CharField(default=app.models.get_default_my_hour, max_length=50),
        ),
    ]
